In [1]:
import numpy as np
import extinction

In [2]:
#          **********     GALACTIC EXTINCTION      **********

# A_V = E(B-V)* R_V    at   R_V = 3.1

# Cardelli, Clayton & Mathis (1989) with R_V = 3.1
# The claimed validity is 1250 Angstroms to 3.3 microns

# extinction.ccm89(wave, 1.0, 3.1)  -- 'wave' in Angstroms

#   ==> Outputs A_lambda i.e. Galactic extinction at given wavelength (in mags)

#  Corrected mags = Observed mags - A_lambda

In [7]:

# sources with their A_V values (galactic-reddening * 3.1)
targets = {'0258': 0.487, '1014': 0.038, '1025': 0.029, '1037': 0.048, '1128': 0.046, 
           '1201': 0.067, '1203': 0.045, '1445': 0.040}


# pivot ~ effective wavelength (angstrom)
filters = {'g': 4810.0, 'r': 6156.3, 'i':7503.7, 'z':8668.5, 'y':9613.4}


Rv = 3.1

In [31]:
temp_array = np.zeros(1)

for key in filters:
    
    wave = np.array([filters[key]])  # input 'wave' has to be a numpy 1-d array 
                                            # with input value as "buffer"/data parameter
    print(key)
    for t in targets:
        
        temp_array[0] = extinction.ccm89(wave, targets[t], Rv)
        gal_ext = round(temp_array[0], 2)
        print(t, gal_ext)

g
0258 0.57
1014 0.04
1025 0.03
1037 0.06
1128 0.05
1201 0.08
1203 0.05
1445 0.05
r
0258 0.43
1014 0.03
1025 0.03
1037 0.04
1128 0.04
1201 0.06
1203 0.04
1445 0.04
i
0258 0.33
1014 0.03
1025 0.02
1037 0.03
1128 0.03
1201 0.05
1203 0.03
1445 0.03
z
0258 0.25
1014 0.02
1025 0.01
1037 0.02
1128 0.02
1201 0.03
1203 0.02
1445 0.02
y
0258 0.21
1014 0.02
1025 0.01
1037 0.02
1128 0.02
1201 0.03
1203 0.02
1445 0.02

In [ ]:
# gal-corrected mags...

In [51]:
import pandas as pd

df = pd.read_csv('panstarrs_isophot.csv', header=0, usecols=[0,1,3,5,7,9], skiprows=[8])
df

     Source      g      r      i      z      y
0   0258+35  13.45  12.02  11.55  10.87   9.66
1  1014+392  22.09  20.33  19.67  19.43  17.55
2  1025+390  19.54  18.00  17.24  16.75  15.87
3   1037+30  16.07  15.25  14.86  14.34  13.23
4  1128+455  21.08  19.38  18.82  18.26  17.01
5  1201+394  21.47  19.70  18.66  18.08  16.66
6  1203+645  23.39  20.14  19.54  18.14  20.98
7  1445+410  19.22  17.77  17.03  16.60  15.46

In [53]:
df = pd.read_csv('panstarrs_isophot.csv', header=0, usecols=[0,1,3,5,7,9], skiprows=[8])
# read again for repeated runs 

temp_array = np.zeros(1)
gal_ext = np.zeros(8)

for key in filters:
    
    i=0
    wave = np.array([filters[key]])  # input 'wave' has to be a numpy 1-d array 
                                            # with input value as "buffer"/data parameter
    print(key)
    for t in targets:
        
        temp_array[0] = extinction.ccm89(wave, targets[t], Rv)
        gal_ext[i] = round(temp_array[0], 2)
  
        band_array = df[key].to_numpy()
        band_array[i] = band_array[i] - gal_ext[i]
        
        i+=1
    
    print(gal_ext)
    print(band_array)

g
[0.57 0.04 0.03 0.06 0.05 0.08 0.05 0.05]
[12.88 22.05 19.51 16.01 21.03 21.39 23.34 19.17]
r
[0.43 0.03 0.03 0.04 0.04 0.06 0.04 0.04]
[11.59 20.3  17.97 15.21 19.34 19.64 20.1  17.73]
i
[0.33 0.03 0.02 0.03 0.03 0.05 0.03 0.03]
[11.22 19.64 17.22 14.83 18.79 18.61 19.51 17.  ]
z
[0.25 0.02 0.01 0.02 0.02 0.03 0.02 0.02]
[10.62 19.41 16.74 14.32 18.24 18.05 18.12 16.58]
y
[0.21 0.02 0.01 0.02 0.02 0.03 0.02 0.02]
[ 9.45 17.53 15.86 13.21 16.99 16.63 20.96 15.44]